name: Ruff

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-uv
        with:
          install-deps: "ruff"
      - name: Run Ruff linter
        run: |
          source .venv/bin/activate
          ruff check .
      - name: Run Ruff formatter
        run: |
          source .venv/bin/activate
          ruff format --check . 